### ISSUE TITLE
plotter_node.py fails to launch

### ISSUE THREAD

**Issue by enceladus2000** [ERC-BPGC/echoslam_ROS#17]
ERROR: cannot launch node of type [echoslam_ROS/plotter_node.py]: can't locate node [plotter_node.py] in package [echoslam_ROS]

BTW fixed the error in robot.py @adbidwai

**Comment by adbidwai** [comment]
Make the plotter_node.py executable in your system using `chmod +x`

**Comment by adbidwai** [comment]
Solved the issue. Sent a new PR.
